version: "3.7"

# Redes
networks:
  wordpress-best-network:

services:
  # Container NGinX que recebe as requests HTTP
  wordpress-best-nginx:
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./logs/nginx:/var/log/nginx

      # Esta pasta esta aqui para os recursos JS, CSS e imagens.
      - ./wordpress:/var/www/html
    depends_on:
      - wordpress-best-php-fpm
    links:
      # Converte o name wordpress-best-php-fpm para ser usado internamente como Wordpress
      - wordpress-best-php-fpm:wordpress
    deploy:
      resources:
        limits:
          cpus: "1.00"
          memory: "128M"
    networks:
      wordpress-best-network:
        aliases:
          - "wordpress-best"

  # Container PHP-FPM que interpreta os arquivos PHP (Somente arquivos PHP chegam aqui)
  wordpress-best-php-fpm:
    build: ./php-fpm
    image: best/wordpress-best-php-fpm
    volumes:
      - ./wordpress:/var/www/html
    depends_on:
      - wordpress-best-memcached
      - wordpress-best-database
    links:
      - wordpress-best-memcached
      - wordpress-best-database
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: "256M"
    networks:
      - wordpress-best-network
    environment: 
      - WORDPRESS_DB_HOST=wordpress-best-database
      - WORDPRESS_DB_USER=dev
      - WORDPRESS_DB_PASSWORD=dev
      - WORDPRESS_DB_NAME=wordpress

  # Container para cache
  wordpress-best-memcached:
    image: memcached:latest
    ports:
      - 11211:11211
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: "64M"

  # Container de banco de dados
  wordpress-best-database:
    image: mariadb:latest
    volumes:
      - ./mysql/data:/var/lib/mysql
    ports:
      - 3306:3306
    deploy:
      resources:
        limits:
          cpus: "1.00"
          memory: "256M"
    networks:
      - wordpress-best-network
    environment: 
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=dev
      - MYSQL_PASSWORD=dev
      - MYSQL_DATABASE=wordpress

  # Container de gestão do MariaDB
  wordpress-best-adminer:
    image: adminer
    links:
      - wordpress-best-database:db
    ports:
      - 8081:8080
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: "128M"
    networks:
      - wordpress-best-network

  # Container para gestão do MemCached
  wordpress-best-phpmemcacheadmin:
    image: hitwe/phpmemcachedadmin
    ports:
      - 8082:80
    links:
      - wordpress-best-memcached:memcached
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: "128M"
    networks:
      - wordpress-best-network

  # Containers de Teste - Selenium - Chrome
  wordpress-best-chrome:
    image: selenium/standalone-chrome-debug:3.141.59-xenon
    volumes:
      - /dev/shm:/dev/shm
    ports:
      - 4444:4444
      - 5900:5900
    deploy:
      resources:
        limits:
          cpus: "1.00"
          memory: "512M"
    networks:
      - wordpress-best-network
